language: python
sudo: false

matrix:
  include:
    - python: '3.6'
      env:
        - INTEGRATION_TEST=true
        - AWS_DEFAULT_REGION=eu-central-1
        - secure: k8/SQDpINDU/fRfYkgVjSyTTgXcuj4W3fcFso+SR8QkQAGF36QjLlNUUA42FLpm0mc1Xr4eCx7YKY4GUMqng5bSncWy/At5OAGLdt1RjG2KY1EhujFtUcW/Co8y2648vNzQrv5FtfIxHlN6OXRHoIAwtV7kNyKHFagunfGpuNqvkvo2Loj1JtqJdV60obG4x0w7dMaKhWWWxbzHs1jZrgyFhpv2508pWkhu/gE1iLlk0iOwNU6IShNRpUcrHfCYocCOyDiT1uiT+WkM14UIMusc1kXWPObcqvRHl84z5KDgAogm5Spc6ep00llh6br+XzL6XZEOkn7K4p0rxF0Z13qEP7OOPuVdx+rwPTUwXVPBH/T5GWC5pKnh1P2Osod73PRWMU2RuYyzWaP535LA/Ub7qlpk18DNyw9stuzZRdkPEwDvZzTkESsTHn8EWkMgB/hyyxK9aJFLoqqoivCNoACXhG96mBpTs0fbjd5swiYhMIT3W61Kmo5eOOyqctT6KV+UEq/+txTnrlt4WeuWYvlD7oJSAKP50l1cQEmVVx0Z3B0HfI7MbtWfzPjZ9a1j15zmKjVMcAvnk32m42d4MzwjYxGsGL5TAvlGvDPUjis3FxeSrDpNfvQkQljEux19E1VZrafqvWXJtfxai5EWU369Uxm5I4KoGlRY5PqAM8Mg=
        - secure: cjYgJ3u0TD0zLfm+PgyCOcwE9ZnmKaM68QEF/JsCAkcD2iz8eYTssBIDMp988+YJHSltptOMBruzy33CnkC1AH6UV+Vp9OyBb38++/U1nUK0QEjZxWNuggDgRGuJ1BbLTjCjFRqHDU2zvKc5zgQUTo056i7TyM9gj7e0RI2gtfF+A2h71Z2MzFFQJAILAlx3TTztqRq2OEQHO2TnBpX+BKDEGhy+mNV+VT+aUHl7ik/khHMK5yyyd6PtVxjHTJBS12VKx6InvxSbT/Eat7SXmFfM9+xDopr4Fw5HV/KG+3mNQAQA+3HsZfTGlECn4tNXdBoABPqVGvfUllbR5OyM8QKlAVQtbJMnpFpFObI2Q3yeWerIeJvp4bgVSSmCdXzg233rOtOreAT2yQjURVaNePwSQtuX9PkFadfTFbfYaRIgjHnBeclE1Dm9zyyxIhHbUx/UfGvYkHxWarXhUDEhGYfhEjm4QVReonO/MYcaQeu7LEEqR0g7PmOWf4cuNfF1SWuDQBGsQU26FXgsGATJGTUoZjkwsPOtInZW0hsmHLwgs0sj6iz3JwvGDfgdv7iX+iebZCYKtBUNv0vq8s7IqY5Fk5m5Ferj+Drb0auUvlQcxotBOE3IupUwpMNLFLXju7TrLU5pjHMeM4dfeFwiXkRBdcZi/QmJEvy2kbf410I=
    - python: '3.6'

addons:
  apt:
    packages:
    - pandoc

before_install:
- pip install --upgrade pip setuptools wheel

install:
- pip install --upgrade pycodestyle pyflakes coverage python-coveralls pytest pytest-cov pypandoc
- python setup.py develop

script:
- if [[ -z "$INTEGRATION_TEST" ]]; then pycodestyle .; fi
- if [[ -z "$INTEGRATION_TEST" ]]; then  pyflakes .; fi
- if [[ -z "$INTEGRATION_TEST" ]]; then py.test --cov=formica tests/unit; fi
- if [[ ! -z "$INTEGRATION_TEST" && ! -z ${AWS_ACCESS_KEY_ID+x} && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then py.test tests/integration; fi

after_success:
- if [[ -z "$INTEGRATION_TEST" ]]; then coveralls; fi


